### ISSUE TITLE
Markdown Code Block Rendering Issue

### ISSUE THREAD

**Issue by unrealcroissant** [tompossin/Studyworx3#3]
When a code block is initiated by four spaces [tab], it renders the text as a single continuous line, ignoring all HTML formatting of the editor and page on which it is rendered.

![2016-05-10-122009_1366x768_scrot](https://cloud.githubusercontent.com/assets/4869909/15164153/380c6600-16ca-11e6-81b4-3946c1fa6242.png)

**Comment by tompossin** [comment]
Not a bug, it is a feature of markdown. 4 spaces or a tab gets translated a
pre tag in HTML.

**Comment by unrealcroissant** [comment]
Right, but is there any reason we _wouldn't_  want to wrap the pre-tags? In the context of Studyworx, that is.

**Comment by tompossin** [comment]
Well that was not something I did. You can add line breaks inside pre tags
but they are not added automatically. This is important if you wish to have
total control of the output. Which is kind of the point of pre tags.
Imagine for example trying to do ASCI art if the browser tossed in line
breaks wherever it felt like it. For those using Studyworx and struggling
with this all you have to do is remind them they have to deliberately add
line breaks where they want them. This is important when doing insides that
look good printed.
Hope that helps,
Tom

**Comment by unrealcroissant** [comment]
Okay that makes sense.
Thanks for the clarification,
Rob
